name: Commit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Configure rust cache
        uses: Swatinem/rust-cache@v1        
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
