name: Commit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    uses: "gracig/actions/.github/workflows/main.yml@main"
    with:
      commit-workflow: "bbw-rust"
      rust-working-directory: "."
